export const actionTypes = {
  GET_MOVIES: 'GET_MOVIES',
  ADD_MOVIE: 'ADD_MOVIE',
  GET_FAV_MOVIES: 'GET_FAV_MOVIES',
  REMOVE_FAV_MOVIE: 'REMOVE_FAV_MOVIE',
  ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
}